#!/bin/bash

echo "GitHub Profile Setup for zenex3298"
echo "=================================="
echo ""
echo "To set up your GitHub profile, follow these steps:"
echo ""
echo "1. Go to https://github.com/new"
echo "2. Create a new repository named: zenex3298"
echo "   (IMPORTANT: The repository name MUST match your username exactly)"
echo "3. Make it PUBLIC"
echo "4. Do NOT initialize with README, .gitignore, or license"
echo "5. After creating, run these commands:"
echo ""
echo "cd ~/branding/zenex3298-profile"
echo "git init"
echo "git add README.md"
echo "git commit -m 'Initial GitHub profile'"
echo "git branch -M main"
echo "git remote add origin https://github.com/zenex3298/zenex3298.git"
echo "git push -u origin main"
echo ""
echo "Your profile README is ready at: ~/branding/zenex3298-profile/README.md"