/**
 * Demo Data - Perfect data for investor presentations
 * All numbers carefully chosen to be impressive but believable
 */

export const DemoData = {
  // Marketer Profile
  marketerProfile: {
    _id: 'demo-marketer-001',
    fullName: 'Sarah Martinez',
    email: 'sarah@techstyle.com',
    company: 'TechStyle Brand',
    balance: 45600,
    totalSpent: 127500,
    activeDeals: 12,
    completedDeals: 47,
    avgDealValue: 2710,
    successRate: 89,
    joinedDate: new Date('2023-01-15'),
    verified: true,
    tier: 'Premium',
  },

  // Creator Profile
  creatorProfile: {
    _id: 'demo-creator-001',
    fullName: 'Alex Chen',
    username: '@alexcreates',
    email: 'alex@creator.com',
    totalEarnings: 45600,
    pendingEarnings: 3200,
    completedDeals: 47,
    activeDeals: 3,
    avgDealValue: 970,
    rating: 4.9,
    responseTime: '2 hours',
    platforms: [
      { platform: 'instagram', followers: 125000, engagement: 8.7 },
      { platform: 'tiktok', followers: 89000, engagement: 12.3 },
      { platform: 'youtube', followers: 45000, engagement: 6.2 },
    ],
  },

  // Offers for Demo
  offers: [
    {
      _id: 'offer-001',
      offerName: 'Summer Collection Launch 2024',
      description: 'Showcase our vibrant summer collection with authentic lifestyle content. Looking for creators who embody confidence and style.',
      proposedAmount: 5000,
      desiredReviewDate: new Date('2024-07-10'),
      desiredPostDate: new Date('2024-07-15'),
      deliverables: ['instagram', 'tiktok'],
      status: 'Active',
      applicants: 23,
      views: 156,
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
      tags: ['Fashion', 'Lifestyle', 'Summer'],
      requirements: [
        '50K+ followers on Instagram',
        'High engagement rate (>5%)',
        'Fashion/lifestyle content focus',
        'Professional photography skills',
      ],
    },
    {
      _id: 'offer-002',
      offerName: 'Tech Product Review Campaign',
      description: 'Create in-depth reviews for our latest smart home devices. Perfect for tech enthusiasts who love exploring innovation.',
      proposedAmount: 3500,
      desiredReviewDate: new Date('2024-07-20'),
      desiredPostDate: new Date('2024-07-25'),
      deliverables: ['youtube', 'instagram'],
      status: 'Active',
      applicants: 18,
      views: 127,
      createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000), // 1 day ago
      tags: ['Technology', 'Reviews', 'Smart Home'],
      requirements: [
        '25K+ YouTube subscribers',
        'Tech content expertise',
        'Video production quality',
        'Detailed review skills',
      ],
    },
    {
      _id: 'offer-003',
      offerName: 'Wellness Journey Partnership',
      description: 'Join our 30-day wellness challenge and document your journey with our fitness products and nutrition plans.',
      proposedAmount: 4200,
      desiredReviewDate: new Date('2024-08-01'),
      desiredPostDate: new Date('2024-08-05'),
      deliverables: ['instagram', 'tiktok', 'youtube'],
      status: 'Active',
      applicants: 31,
      views: 203,
      createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000), // 3 days ago
      tags: ['Fitness', 'Wellness', 'Health'],
      requirements: [
        '40K+ combined followers',
        'Health & fitness focus',
        '30-day commitment',
        'Authentic storytelling',
      ],
    },
  ],

  // High-Quality Creator Profiles - Expanded for Investor Demo
  creators: [
    {
      _id: 'creator-001',
      name: 'Emma Thompson',
      userName: '@emmastyle',
      avatarUrl: 'https://randomuser.me/api/portraits/women/1.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Fashion & Lifestyle Creator | Sustainable Fashion Advocate | Style Consultant',
      location: 'Los Angeles, CA',
      rating: 4.9,
      completedDeals: 34,
      responseTime: '1 hour',
      joinedDate: new Date('2022-03-15'),
      verified: true,
      creatorData: {
        totalFollowers: 254000,
        platforms: [
          { platform: 'instagram', handle: '@emmastyle', followersCount: 156000, engagement: 8.9, verified: true },
          { platform: 'tiktok', handle: '@emmastyle', followersCount: 98000, engagement: 11.2 },
        ],
        categories: ['Fashion', 'Lifestyle', 'Sustainability'],
        portfolioHighlights: ['Vogue Feature', 'NYFW 2023', 'EcoStyle Award'],
        avgDealValue: 3200,
        specialties: ['Sustainable Fashion', 'Style Consulting', 'Brand Partnerships'],
      },
    },
    {
      _id: 'creator-002',
      name: 'Marcus Johnson',
      userName: '@techmarc',
      avatarUrl: 'https://randomuser.me/api/portraits/men/2.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Tech Reviewer | Smart Home Enthusiast | Future Tech Explorer',
      location: 'San Francisco, CA',
      rating: 4.8,
      completedDeals: 28,
      responseTime: '3 hours',
      joinedDate: new Date('2021-11-22'),
      verified: true,
      creatorData: {
        totalFollowers: 279000,
        platforms: [
          { platform: 'youtube', handle: '@TechMarcReviews', followersCount: 234000, engagement: 7.2, verified: true },
          { platform: 'twitter', handle: '@techmarc', followersCount: 45000, engagement: 5.8 },
        ],
        categories: ['Technology', 'Reviews', 'Tutorials'],
        portfolioHighlights: ['CES Speaker 2023', 'Top Tech Influencer', '1M+ Monthly Views'],
        avgDealValue: 4800,
        specialties: ['Product Reviews', 'Tech Tutorials', 'Unboxing Videos'],
      },
    },
    {
      _id: 'creator-003',
      name: 'Sofia Rodriguez',
      userName: '@sofiafit',
      avatarUrl: 'https://randomuser.me/api/portraits/women/3.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Certified Personal Trainer | Nutrition Coach | Wellness Advocate',
      location: 'Miami, FL',
      rating: 5.0,
      completedDeals: 41,
      responseTime: '30 minutes',
      joinedDate: new Date('2022-01-08'),
      verified: true,
      creatorData: {
        totalFollowers: 267000,
        platforms: [
          { platform: 'instagram', handle: '@sofiafit', followersCount: 189000, engagement: 9.8, verified: true },
          { platform: 'youtube', handle: '@SofiaFitness', followersCount: 78000, engagement: 8.1 },
        ],
        categories: ['Fitness', 'Health', 'Nutrition'],
        portfolioHighlights: ['Nike Partnership', 'Fitness App Launch', 'TEDx Speaker'],
        avgDealValue: 2800,
        specialties: ['Workout Routines', 'Nutrition Tips', 'Wellness Coaching'],
      },
    },
    {
      _id: 'creator-004',
      name: 'Jake Miller',
      userName: '@jakeeats',
      avatarUrl: 'https://randomuser.me/api/portraits/men/4.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Food Enthusiast | Recipe Developer | Restaurant Reviewer',
      location: 'New York, NY',
      rating: 4.7,
      completedDeals: 52,
      responseTime: '2 hours',
      joinedDate: new Date('2021-09-14'),
      verified: true,
      creatorData: {
        totalFollowers: 423000,
        platforms: [
          { platform: 'instagram', handle: '@jakeeats', followersCount: 267000, engagement: 12.4, verified: true },
          { platform: 'tiktok', handle: '@jakeeats', followersCount: 156000, engagement: 15.8 },
        ],
        categories: ['Food', 'Lifestyle', 'Reviews'],
        portfolioHighlights: ['Food Network Feature', 'Michelin Guide Contributor', 'Top Food Creator 2023'],
        avgDealValue: 3600,
        specialties: ['Recipe Creation', 'Restaurant Reviews', 'Food Photography'],
      },
    },
    {
      _id: 'creator-005',
      name: 'Maya Patel',
      userName: '@mayatravels',
      avatarUrl: 'https://randomuser.me/api/portraits/women/5.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Travel Photographer | Adventure Seeker | Cultural Explorer',
      location: 'Austin, TX',
      rating: 4.9,
      completedDeals: 37,
      responseTime: '4 hours',
      joinedDate: new Date('2022-05-20'),
      verified: true,
      creatorData: {
        totalFollowers: 312000,
        platforms: [
          { platform: 'instagram', handle: '@mayatravels', followersCount: 198000, engagement: 9.3, verified: true },
          { platform: 'youtube', handle: '@MayaWanderlust', followersCount: 114000, engagement: 7.6 },
        ],
        categories: ['Travel', 'Photography', 'Adventure'],
        portfolioHighlights: ['National Geographic Feature', 'Travel Blogger Award', '50+ Countries Visited'],
        avgDealValue: 4200,
        specialties: ['Travel Photography', 'Destination Guides', 'Adventure Content'],
      },
    },
    {
      _id: 'creator-006',
      name: 'Tyler Brooks',
      userName: '@carguytyl',
      avatarUrl: 'https://randomuser.me/api/portraits/men/6.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Automotive Enthusiast | Racing Driver | Car Reviewer',
      location: 'Detroit, MI',
      rating: 4.8,
      completedDeals: 29,
      responseTime: '2 hours',
      joinedDate: new Date('2021-07-11'),
      verified: true,
      creatorData: {
        totalFollowers: 387000,
        platforms: [
          { platform: 'youtube', handle: '@CarGuyTyler', followersCount: 289000, engagement: 8.9, verified: true },
          { platform: 'instagram', handle: '@carguytyl', followersCount: 98000, engagement: 11.2 },
        ],
        categories: ['Automotive', 'Racing', 'Reviews'],
        portfolioHighlights: ['Formula Drift Partner', 'SEMA Featured Creator', 'Car & Driver Contributor'],
        avgDealValue: 5200,
        specialties: ['Car Reviews', 'Racing Content', 'Automotive News'],
      },
    },
    {
      _id: 'creator-007',
      name: 'Ashley Kim',
      userName: '@beautybyash',
      avatarUrl: 'https://randomuser.me/api/portraits/women/7.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Beauty Expert | Makeup Artist | Skincare Specialist',
      location: 'Los Angeles, CA',
      rating: 4.9,
      completedDeals: 63,
      responseTime: '1 hour',
      joinedDate: new Date('2020-12-03'),
      verified: true,
      creatorData: {
        totalFollowers: 445000,
        platforms: [
          { platform: 'instagram', handle: '@beautybyash', followersCount: 278000, engagement: 13.7, verified: true },
          { platform: 'tiktok', handle: '@beautybyash', followersCount: 167000, engagement: 18.4 },
        ],
        categories: ['Beauty', 'Skincare', 'Lifestyle'],
        portfolioHighlights: ['Sephora Partnership', 'Beauty Influencer Awards', 'Makeup Masterclass Series'],
        avgDealValue: 3800,
        specialties: ['Makeup Tutorials', 'Product Reviews', 'Skincare Routines'],
      },
    },
    {
      _id: 'creator-008',
      name: 'David Chen',
      userName: '@gamerdave',
      avatarUrl: 'https://randomuser.me/api/portraits/men/8.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Professional Gamer | Game Reviewer | Esports Commentator',
      location: 'Seattle, WA',
      rating: 4.6,
      completedDeals: 31,
      responseTime: '3 hours',
      joinedDate: new Date('2021-10-17'),
      verified: true,
      creatorData: {
        totalFollowers: 512000,
        platforms: [
          { platform: 'youtube', handle: '@GamerDaveReviews', followersCount: 345000, engagement: 9.1, verified: true },
          { platform: 'twitch', handle: '@gamerdave', followersCount: 167000, engagement: 14.3 },
        ],
        categories: ['Gaming', 'Technology', 'Entertainment'],
        portfolioHighlights: ['ESL Tournament Commentator', 'Gaming Hardware Partner', 'Top Gaming Creator 2023'],
        avgDealValue: 4600,
        specialties: ['Game Reviews', 'Hardware Testing', 'Live Streaming'],
      },
    },
    {
      _id: 'creator-009',
      name: 'Luna Martinez',
      userName: '@homedecor_luna',
      avatarUrl: 'https://randomuser.me/api/portraits/women/9.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Interior Designer | Home Decor Expert | DIY Enthusiast',
      location: 'Phoenix, AZ',
      rating: 4.8,
      completedDeals: 44,
      responseTime: '2 hours',
      joinedDate: new Date('2022-02-28'),
      verified: true,
      creatorData: {
        totalFollowers: 234000,
        platforms: [
          { platform: 'instagram', handle: '@homedecor_luna', followersCount: 156000, engagement: 10.6, verified: true },
          { platform: 'pinterest', handle: '@lunadesigns', followersCount: 78000, engagement: 8.9 },
        ],
        categories: ['Home Decor', 'DIY', 'Lifestyle'],
        portfolioHighlights: ['HGTV Feature', 'Home & Garden Magazine', 'Interior Design Awards'],
        avgDealValue: 2900,
        specialties: ['Room Makeovers', 'DIY Projects', 'Home Styling'],
      },
    },
    {
      _id: 'creator-010',
      name: 'Ryan Thompson',
      userName: '@outdooryan',
      avatarUrl: 'https://randomuser.me/api/portraits/men/10.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Outdoor Adventure Guide | Hiking Expert | Nature Photographer',
      location: 'Denver, CO',
      rating: 4.9,
      completedDeals: 26,
      responseTime: '5 hours',
      joinedDate: new Date('2022-06-12'),
      verified: true,
      creatorData: {
        totalFollowers: 189000,
        platforms: [
          { platform: 'instagram', handle: '@outdooryan', followersCount: 123000, engagement: 11.8, verified: true },
          { platform: 'youtube', handle: '@OutdoorAdventuresRyan', followersCount: 66000, engagement: 7.4 },
        ],
        categories: ['Outdoor', 'Adventure', 'Photography'],
        portfolioHighlights: ['Outside Magazine Feature', 'REI Brand Partner', 'National Parks Ambassador'],
        avgDealValue: 3400,
        specialties: ['Hiking Guides', 'Gear Reviews', 'Nature Photography'],
      },
    },
    {
      _id: 'creator-011',
      name: 'Zoe Williams',
      userName: '@parentingwithzoe',
      avatarUrl: 'https://randomuser.me/api/portraits/women/11.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Parenting Expert | Family Lifestyle | Child Development Specialist',
      location: 'Chicago, IL',
      rating: 5.0,
      completedDeals: 38,
      responseTime: '1 hour',
      joinedDate: new Date('2021-04-09'),
      verified: true,
      creatorData: {
        totalFollowers: 198000,
        platforms: [
          { platform: 'instagram', handle: '@parentingwithzoe', followersCount: 134000, engagement: 12.3, verified: true },
          { platform: 'youtube', handle: '@ZoeParentingTips', followersCount: 64000, engagement: 8.7 },
        ],
        categories: ['Parenting', 'Family', 'Education'],
        portfolioHighlights: ['Parenting Magazine Contributor', 'Child Development Certification', 'Family Brand Partnerships'],
        avgDealValue: 2600,
        specialties: ['Parenting Tips', 'Child Development', 'Family Activities'],
      },
    },
    {
      _id: 'creator-012',
      name: 'Alex Rivera',
      userName: '@musicproduceralex',
      avatarUrl: 'https://randomuser.me/api/portraits/men/12.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Music Producer | Beat Maker | Audio Engineering Expert',
      location: 'Nashville, TN',
      rating: 4.7,
      completedDeals: 22,
      responseTime: '4 hours',
      joinedDate: new Date('2022-08-15'),
      verified: true,
      creatorData: {
        totalFollowers: 167000,
        platforms: [
          { platform: 'youtube', handle: '@AlexRiveraBeats', followersCount: 98000, engagement: 9.5, verified: true },
          { platform: 'instagram', handle: '@musicproduceralex', followersCount: 69000, engagement: 10.8 },
        ],
        categories: ['Music', 'Audio', 'Entertainment'],
        portfolioHighlights: ['Grammy Nominated Producer', 'Music Production Courses', 'Industry Collaborations'],
        avgDealValue: 4100,
        specialties: ['Beat Making', 'Audio Production', 'Music Education'],
      },
    },
    {
      _id: 'creator-013',
      name: 'Chloe Davis',
      userName: '@petlover_chloe',
      avatarUrl: 'https://randomuser.me/api/portraits/women/13.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Pet Care Expert | Animal Trainer | Veterinary Student',
      location: 'Portland, OR',
      rating: 4.8,
      completedDeals: 33,
      responseTime: '2 hours',
      joinedDate: new Date('2021-12-07'),
      verified: true,
      creatorData: {
        totalFollowers: 223000,
        platforms: [
          { platform: 'instagram', handle: '@petlover_chloe', followersCount: 145000, engagement: 14.2, verified: true },
          { platform: 'tiktok', handle: '@chloepets', followersCount: 78000, engagement: 16.7 },
        ],
        categories: ['Pets', 'Animals', 'Education'],
        portfolioHighlights: ['Veterinary Student', 'Pet Brand Partnerships', 'Animal Rescue Advocate'],
        avgDealValue: 2400,
        specialties: ['Pet Care Tips', 'Animal Training', 'Pet Product Reviews'],
      },
    },
    {
      _id: 'creator-014',
      name: 'Jordan Smith',
      userName: '@businessjordan',
      avatarUrl: 'https://randomuser.me/api/portraits/men/14.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Business Coach | Entrepreneur | Startup Advisor',
      location: 'Dallas, TX',
      rating: 4.9,
      completedDeals: 19,
      responseTime: '3 hours',
      joinedDate: new Date('2022-11-21'),
      verified: true,
      creatorData: {
        totalFollowers: 134000,
        platforms: [
          { platform: 'linkedin', handle: '@jordansmithbiz', followersCount: 89000, engagement: 7.8, verified: true },
          { platform: 'youtube', handle: '@BusinessWithJordan', followersCount: 45000, engagement: 6.9 },
        ],
        categories: ['Business', 'Finance', 'Education'],
        portfolioHighlights: ['Forbes 30 Under 30', 'Business Podcast Host', 'Startup Accelerator Mentor'],
        avgDealValue: 5800,
        specialties: ['Business Strategy', 'Entrepreneurship', 'Leadership Training'],
      },
    },
    {
      _id: 'creator-015',
      name: 'Isabella Garcia',
      userName: '@plantmom_isa',
      avatarUrl: 'https://randomuser.me/api/portraits/women/15.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Plant Expert | Gardening Enthusiast | Sustainable Living Advocate',
      location: 'San Diego, CA',
      rating: 4.8,
      completedDeals: 27,
      responseTime: '3 hours',
      joinedDate: new Date('2022-04-18'),
      verified: true,
      creatorData: {
        totalFollowers: 178000,
        platforms: [
          { platform: 'instagram', handle: '@plantmom_isa', followersCount: 112000, engagement: 13.1, verified: true },
          { platform: 'youtube', handle: '@IsabellaGardens', followersCount: 66000, engagement: 8.3 },
        ],
        categories: ['Plants', 'Gardening', 'Sustainability'],
        portfolioHighlights: ['Botany Degree', 'Garden Center Partnership', 'Sustainable Living Expert'],
        avgDealValue: 2700,
        specialties: ['Plant Care', 'Garden Design', 'Sustainable Practices'],
      },
    },
  ],

  // Analytics Data
  analytics: {
    overview: {
      totalRevenue: 485600,
      monthlyGrowth: 23.5,
      activeUsers: 3420,
      completedDeals: 892,
    },
    recentActivity: [
      { type: 'deal_completed', amount: 3500, time: '2 hours ago', creator: 'Emma Thompson' },
      { type: 'payment_sent', amount: 2800, time: '5 hours ago', creator: 'Marcus Johnson' },
      { type: 'offer_accepted', amount: 4200, time: '1 day ago', creator: 'Sofia Rodriguez' },
      { type: 'milestone_completed', amount: 1500, time: '2 days ago', creator: 'Alex Chen' },
    ],
    performanceMetrics: {
      avgDealCompletion: 8.5, // days
      creatorSatisfaction: 4.8,
      brandRetention: 92,
      platformGrowth: 156, // percentage YoY
    },
  },

  // Demo Notifications
  notifications: [
    {
      id: 'notif-001',
      type: 'application',
      message: 'Emma Thompson applied to your Summer Collection offer',
      time: '2 minutes ago',
      unread: true,
    },
    {
      id: 'notif-002',
      type: 'milestone',
      message: 'Marcus Johnson completed the product review',
      time: '1 hour ago',
      unread: true,
    },
    {
      id: 'notif-003',
      type: 'payment',
      message: 'Payment of $3,500 processed successfully',
      time: '3 hours ago',
      unread: false,
    },
  ],

  // Success Messages
  successMessages: {
    offerCreated: 'Offer published! 23 creators viewing now',
    applicationAccepted: 'Great choice! Emma Thompson is perfect for this campaign',
    paymentProcessed: 'Payment successful! Campaign is now live',
    dealCompleted: 'Congratulations! Another successful collaboration',
  },
};