/**
 * Demo Data - Perfect data for investor presentations
 * All numbers carefully chosen to be impressive but believable
 */

export const DemoData = {
  // Marketer Profile
  marketerProfile: {
    _id: 'demo-marketer-001',
    fullName: 'Sarah Martinez',
    email: 'sarah@techstyle.com',
    company: 'TechStyle Brand',
    balance: 45600,
    totalSpent: 127500,
    activeDeals: 12,
    completedDeals: 47,
    avgDealValue: 2710,
    successRate: 89,
    joinedDate: new Date('2023-01-15'),
    verified: true,
    tier: 'Premium',
  },

  // Creator Profile
  creatorProfile: {
    _id: 'demo-creator-001',
    fullName: 'Alex Chen',
    username: '@alexcreates',
    email: 'alex@creator.com',
    totalEarnings: 45600,
    pendingEarnings: 3200,
    completedDeals: 47,
    activeDeals: 3,
    avgDealValue: 970,
    rating: 4.9,
    responseTime: '2 hours',
    platforms: [
      { platform: 'instagram', followers: 125000, engagement: 8.7 },
      { platform: 'tiktok', followers: 89000, engagement: 12.3 },
      { platform: 'youtube', followers: 45000, engagement: 6.2 },
    ],
  },

  // Offers for Demo
  offers: [
    {
      _id: 'offer-001',
      offerName: 'Summer Collection Launch 2024',
      description: 'Showcase our vibrant summer collection with authentic lifestyle content. Looking for creators who embody confidence and style.',
      proposedAmount: 5000,
      desiredReviewDate: new Date('2024-07-10'),
      desiredPostDate: new Date('2024-07-15'),
      deliverables: ['instagram', 'tiktok'],
      status: 'Active',
      applicants: 23,
      views: 156,
      createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
      tags: ['Fashion', 'Lifestyle', 'Summer'],
      requirements: [
        '50K+ followers on Instagram',
        'High engagement rate (>5%)',
        'Fashion/lifestyle content focus',
        'Professional photography skills',
      ],
    },
    {
      _id: 'offer-002',
      offerName: 'Tech Product Review Campaign',
      description: 'Create in-depth reviews for our latest smart home devices. Perfect for tech enthusiasts who love exploring innovation.',
      proposedAmount: 3500,
      desiredReviewDate: new Date('2024-07-20'),
      desiredPostDate: new Date('2024-07-25'),
      deliverables: ['youtube', 'instagram'],
      status: 'Active',
      applicants: 18,
      views: 127,
      createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000), // 1 day ago
      tags: ['Technology', 'Reviews', 'Smart Home'],
      requirements: [
        '25K+ YouTube subscribers',
        'Tech content expertise',
        'Video production quality',
        'Detailed review skills',
      ],
    },
    {
      _id: 'offer-003',
      offerName: 'Wellness Journey Partnership',
      description: 'Join our 30-day wellness challenge and document your journey with our fitness products and nutrition plans.',
      proposedAmount: 4200,
      desiredReviewDate: new Date('2024-08-01'),
      desiredPostDate: new Date('2024-08-05'),
      deliverables: ['instagram', 'tiktok', 'youtube'],
      status: 'Active',
      applicants: 31,
      views: 203,
      createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000), // 3 days ago
      tags: ['Fitness', 'Wellness', 'Health'],
      requirements: [
        '40K+ combined followers',
        'Health & fitness focus',
        '30-day commitment',
        'Authentic storytelling',
      ],
    },
  ],

  // High-Quality Creator Profiles - Expanded for Investor Demo
  creators: [
    {
      _id: 'creator-001',
      name: 'Emma Thompson',
      userName: '@emmastyle',
      avatarUrl: 'https://randomuser.me/api/portraits/women/1.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Fashion & Lifestyle Creator | Sustainable Fashion Advocate | Style Consultant',
      location: 'Los Angeles, CA',
      rating: 4.9,
      completedDeals: 34,
      responseTime: '1 hour',
      joinedDate: new Date('2022-03-15'),
      verified: true,
      creatorData: {
        totalFollowers: 254000,
        platforms: [
          { platform: 'instagram', handle: '@emmastyle', followersCount: 156000, engagement: 8.9, verified: true },
          { platform: 'tiktok', handle: '@emmastyle', followersCount: 98000, engagement: 11.2 },
        ],
        categories: ['Fashion', 'Lifestyle', 'Sustainability'],
        portfolioHighlights: ['Vogue Feature', 'NYFW 2023', 'EcoStyle Award'],
        avgDealValue: 3200,
        specialties: ['Sustainable Fashion', 'Style Consulting', 'Brand Partnerships'],
      },
    },
    {
      _id: 'creator-002',
      name: 'Marcus Johnson',
      userName: '@techmarc',
      avatarUrl: 'https://randomuser.me/api/portraits/men/2.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Tech Reviewer | Smart Home Enthusiast | Future Tech Explorer',
      location: 'San Francisco, CA',
      rating: 4.8,
      completedDeals: 28,
      responseTime: '3 hours',
      joinedDate: new Date('2021-11-22'),
      verified: true,
      creatorData: {
        totalFollowers: 279000,
        platforms: [
          { platform: 'youtube', handle: '@TechMarcReviews', followersCount: 234000, engagement: 7.2, verified: true },
          { platform: 'twitter', handle: '@techmarc', followersCount: 45000, engagement: 5.8 },
        ],
        categories: ['Technology', 'Reviews', 'Tutorials'],
        portfolioHighlights: ['CES Speaker 2023', 'Top Tech Influencer', '1M+ Monthly Views'],
        avgDealValue: 4800,
        specialties: ['Product Reviews', 'Tech Tutorials', 'Unboxing Videos'],
      },
    },
    {
      _id: 'creator-003',
      name: 'Sofia Rodriguez',
      userName: '@sofiafit',
      avatarUrl: 'https://randomuser.me/api/portraits/women/3.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Certified Personal Trainer | Nutrition Coach | Wellness Advocate',
      location: 'Miami, FL',
      rating: 5.0,
      completedDeals: 41,
      responseTime: '30 minutes',
      joinedDate: new Date('2022-01-08'),
      verified: true,
      creatorData: {
        totalFollowers: 267000,
        platforms: [
          { platform: 'instagram', handle: '@sofiafit', followersCount: 189000, engagement: 9.8, verified: true },
          { platform: 'youtube', handle: '@SofiaFitness', followersCount: 78000, engagement: 8.1 },
        ],
        categories: ['Fitness', 'Health', 'Nutrition'],
        portfolioHighlights: ['Nike Partnership', 'Fitness App Launch', 'TEDx Speaker'],
        avgDealValue: 2800,
        specialties: ['Workout Routines', 'Nutrition Tips', 'Wellness Coaching'],
      },
    },
    {
      _id: 'creator-004',
      name: 'Jake Miller',
      userName: '@jakeeats',
      avatarUrl: 'https://randomuser.me/api/portraits/men/4.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Food Enthusiast | Recipe Developer | Restaurant Reviewer',
      location: 'New York, NY',
      rating: 4.7,
      completedDeals: 52,
      responseTime: '2 hours',
      joinedDate: new Date('2021-09-14'),
      verified: true,
      creatorData: {
        totalFollowers: 423000,
        platforms: [
          { platform: 'instagram', handle: '@jakeeats', followersCount: 267000, engagement: 12.4, verified: true },
          { platform: 'tiktok', handle: '@jakeeats', followersCount: 156000, engagement: 15.8 },
        ],
        categories: ['Food', 'Lifestyle', 'Reviews'],
        portfolioHighlights: ['Food Network Feature', 'Michelin Guide Contributor', 'Top Food Creator 2023'],
        avgDealValue: 3600,
        specialties: ['Recipe Creation', 'Restaurant Reviews', 'Food Photography'],
      },
    },
    {
      _id: 'creator-005',
      name: 'Maya Patel',
      userName: '@mayatravels',
      avatarUrl: 'https://randomuser.me/api/portraits/women/5.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Travel Photographer | Adventure Seeker | Cultural Explorer',
      location: 'Austin, TX',
      rating: 4.9,
      completedDeals: 37,
      responseTime: '4 hours',
      joinedDate: new Date('2022-05-20'),
      verified: true,
      creatorData: {
        totalFollowers: 312000,
        platforms: [
          { platform: 'instagram', handle: '@mayatravels', followersCount: 198000, engagement: 9.3, verified: true },
          { platform: 'youtube', handle: '@MayaWanderlust', followersCount: 114000, engagement: 7.6 },
        ],
        categories: ['Travel', 'Photography', 'Adventure'],
        portfolioHighlights: ['National Geographic Feature', 'Travel Blogger Award', '50+ Countries Visited'],
        avgDealValue: 4200,
        specialties: ['Travel Photography', 'Destination Guides', 'Adventure Content'],
      },
    },
    {
      _id: 'creator-001', // Replacing Emma Thompson with Amelia Hilpert
      name: 'Amelia Hilpert',
      userName: 'dayana94',
      avatarUrl: 'https://i.imghippo.com/files/ZlC5621Wbw.jpeg',
      isActive: true,
      userType: 'Creator',
      bio: 'Victoria blandior totam appono acerbitas utor sequi advoco.',
      location: 'Los Angeles, CA',
      rating: 4.9,
      completedDeals: 12,
      responseTime: '1 hour',
      joinedDate: new Date('2022-03-15'),
      verified: true,
      tier: 'Macro', // New field for tier
      creatorData: {
        totalFollowers: 3400000, // 3.4M total followers
        platforms: [
          { platform: 'twitter', handle: '@dayana94', followersCount: 478900, engagement: 8.9, verified: true },
          { platform: 'instagram', handle: '@dayana94', followersCount: 1900000, engagement: 11.2 },
          { platform: 'youtube', handle: '@dayana94', followersCount: 630500, engagement: 7.2 },
          { platform: 'facebook', handle: 'dayana94', followersCount: 437700, engagement: 5.8 },
        ],
        categories: ['Racing'],
        portfolioHighlights: ['Upgradable local capability', 'Persevering systemic knowledge user'],
        businessVentures: ['Horizontal responsive microservice', 'Quality-focused discrete support'],
        avgDealValue: 3200,
        specialties: ['Racing', 'Macro Influencer', 'Brand Partnerships'],
        listedEvents: 83,
        combinedViews: 2600,
        offers: 36,
        deals: 12,
      },
    },
    {
      _id: 'creator-006',
      name: 'Tyler Brooks',
      userName: '@carguytyl',
      avatarUrl: 'https://randomuser.me/api/portraits/men/6.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Automotive Enthusiast | Racing Driver | Car Reviewer',
      location: 'Detroit, MI',
      rating: 4.8,
      completedDeals: 29,
      responseTime: '2 hours',
      joinedDate: new Date('2021-07-11'),
      verified: true,
      creatorData: {
        totalFollowers: 387000,
        platforms: [
          { platform: 'youtube', handle: '@CarGuyTyler', followersCount: 289000, engagement: 8.9, verified: true },
          { platform: 'instagram', handle: '@carguytyl', followersCount: 98000, engagement: 11.2 },
        ],
        categories: ['Automotive', 'Racing', 'Reviews'],
        portfolioHighlights: ['Formula Drift Partner', 'SEMA Featured Creator', 'Car & Driver Contributor'],
        avgDealValue: 5200,
        specialties: ['Car Reviews', 'Racing Content', 'Automotive News'],
      },
    },
    {
      _id: 'creator-007',
      name: 'Ashley Kim',
      userName: '@beautybyash',
      avatarUrl: 'https://randomuser.me/api/portraits/women/7.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Beauty Expert | Makeup Artist | Skincare Specialist',
      location: 'Los Angeles, CA',
      rating: 4.9,
      completedDeals: 63,
      responseTime: '1 hour',
      joinedDate: new Date('2020-12-03'),
      verified: true,
      creatorData: {
        totalFollowers: 445000,
        platforms: [
          { platform: 'instagram', handle: '@beautybyash', followersCount: 278000, engagement: 13.7, verified: true },
          { platform: 'tiktok', handle: '@beautybyash', followersCount: 167000, engagement: 18.4 },
        ],
        categories: ['Beauty', 'Skincare', 'Lifestyle'],
        portfolioHighlights: ['Sephora Partnership', 'Beauty Influencer Awards', 'Makeup Masterclass Series'],
        avgDealValue: 3800,
        specialties: ['Makeup Tutorials', 'Product Reviews', 'Skincare Routines'],
      },
    },
    {
      _id: 'creator-008',
      name: 'David Chen',
      userName: '@gamerdave',
      avatarUrl: 'https://randomuser.me/api/portraits/men/8.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Professional Gamer | Game Reviewer | Esports Commentator',
      location: 'Seattle, WA',
      rating: 4.6,
      completedDeals: 31,
      responseTime: '3 hours',
      joinedDate: new Date('2021-10-17'),
      verified: true,
      creatorData: {
        totalFollowers: 512000,
        platforms: [
          { platform: 'youtube', handle: '@GamerDaveReviews', followersCount: 345000, engagement: 9.1, verified: true },
          { platform: 'twitch', handle: '@gamerdave', followersCount: 167000, engagement: 14.3 },
        ],
        categories: ['Gaming', 'Technology', 'Entertainment'],
        portfolioHighlights: ['ESL Tournament Commentator', 'Gaming Hardware Partner', 'Top Gaming Creator 2023'],
        avgDealValue: 4600,
        specialties: ['Game Reviews', 'Hardware Testing', 'Live Streaming'],
      },
    },
    {
      _id: 'creator-009',
      name: 'Luna Martinez',
      userName: '@homedecor_luna',
      avatarUrl: 'https://randomuser.me/api/portraits/women/9.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Interior Designer | Home Decor Expert | DIY Enthusiast',
      location: 'Phoenix, AZ',
      rating: 4.8,
      completedDeals: 44,
      responseTime: '2 hours',
      joinedDate: new Date('2022-02-28'),
      verified: true,
      creatorData: {
        totalFollowers: 234000,
        platforms: [
          { platform: 'instagram', handle: '@homedecor_luna', followersCount: 156000, engagement: 10.6, verified: true },
          { platform: 'pinterest', handle: '@lunadesigns', followersCount: 78000, engagement: 8.9 },
        ],
        categories: ['Home Decor', 'DIY', 'Lifestyle'],
        portfolioHighlights: ['HGTV Feature', 'Home & Garden Magazine', 'Interior Design Awards'],
        avgDealValue: 2900,
        specialties: ['Room Makeovers', 'DIY Projects', 'Home Styling'],
      },
    },
    {
      _id: 'creator-010',
      name: 'Ryan Thompson',
      userName: '@outdooryan',
      avatarUrl: 'https://randomuser.me/api/portraits/men/10.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Outdoor Adventure Guide | Hiking Expert | Nature Photographer',
      location: 'Denver, CO',
      rating: 4.9,
      completedDeals: 26,
      responseTime: '5 hours',
      joinedDate: new Date('2022-06-12'),
      verified: true,
      creatorData: {
        totalFollowers: 189000,
        platforms: [
          { platform: 'instagram', handle: '@outdooryan', followersCount: 123000, engagement: 11.8, verified: true },
          { platform: 'youtube', handle: '@OutdoorAdventuresRyan', followersCount: 66000, engagement: 7.4 },
        ],
        categories: ['Outdoor', 'Adventure', 'Photography'],
        portfolioHighlights: ['Outside Magazine Feature', 'REI Brand Partner', 'National Parks Ambassador'],
        avgDealValue: 3400,
        specialties: ['Hiking Guides', 'Gear Reviews', 'Nature Photography'],
      },
    },
    {
      _id: 'creator-011',
      name: 'Zoe Williams',
      userName: '@parentingwithzoe',
      avatarUrl: 'https://randomuser.me/api/portraits/women/11.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Parenting Expert | Family Lifestyle | Child Development Specialist',
      location: 'Chicago, IL',
      rating: 5.0,
      completedDeals: 38,
      responseTime: '1 hour',
      joinedDate: new Date('2021-04-09'),
      verified: true,
      creatorData: {
        totalFollowers: 198000,
        platforms: [
          { platform: 'instagram', handle: '@parentingwithzoe', followersCount: 134000, engagement: 12.3, verified: true },
          { platform: 'youtube', handle: '@ZoeParentingTips', followersCount: 64000, engagement: 8.7 },
        ],
        categories: ['Parenting', 'Family', 'Education'],
        portfolioHighlights: ['Parenting Magazine Contributor', 'Child Development Certification', 'Family Brand Partnerships'],
        avgDealValue: 2600,
        specialties: ['Parenting Tips', 'Child Development', 'Family Activities'],
      },
    },
    {
      _id: 'creator-012',
      name: 'Alex Rivera',
      userName: '@musicproduceralex',
      avatarUrl: 'https://randomuser.me/api/portraits/men/12.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Music Producer | Beat Maker | Audio Engineering Expert',
      location: 'Nashville, TN',
      rating: 4.7,
      completedDeals: 22,
      responseTime: '4 hours',
      joinedDate: new Date('2022-08-15'),
      verified: true,
      creatorData: {
        totalFollowers: 167000,
        platforms: [
          { platform: 'youtube', handle: '@AlexRiveraBeats', followersCount: 98000, engagement: 9.5, verified: true },
          { platform: 'instagram', handle: '@musicproduceralex', followersCount: 69000, engagement: 10.8 },
        ],
        categories: ['Music', 'Audio', 'Entertainment'],
        portfolioHighlights: ['Grammy Nominated Producer', 'Music Production Courses', 'Industry Collaborations'],
        avgDealValue: 4100,
        specialties: ['Beat Making', 'Audio Production', 'Music Education'],
      },
    },
    {
      _id: 'creator-013',
      name: 'Chloe Davis',
      userName: '@petlover_chloe',
      avatarUrl: 'https://randomuser.me/api/portraits/women/13.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Pet Care Expert | Animal Trainer | Veterinary Student',
      location: 'Portland, OR',
      rating: 4.8,
      completedDeals: 33,
      responseTime: '2 hours',
      joinedDate: new Date('2021-12-07'),
      verified: true,
      creatorData: {
        totalFollowers: 223000,
        platforms: [
          { platform: 'instagram', handle: '@petlover_chloe', followersCount: 145000, engagement: 14.2, verified: true },
          { platform: 'tiktok', handle: '@chloepets', followersCount: 78000, engagement: 16.7 },
        ],
        categories: ['Pets', 'Animals', 'Education'],
        portfolioHighlights: ['Veterinary Student', 'Pet Brand Partnerships', 'Animal Rescue Advocate'],
        avgDealValue: 2400,
        specialties: ['Pet Care Tips', 'Animal Training', 'Pet Product Reviews'],
      },
    },
    {
      _id: 'creator-014',
      name: 'Jordan Smith',
      userName: '@businessjordan',
      avatarUrl: 'https://randomuser.me/api/portraits/men/14.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Business Coach | Entrepreneur | Startup Advisor',
      location: 'Dallas, TX',
      rating: 4.9,
      completedDeals: 19,
      responseTime: '3 hours',
      joinedDate: new Date('2022-11-21'),
      verified: true,
      creatorData: {
        totalFollowers: 134000,
        platforms: [
          { platform: 'linkedin', handle: '@jordansmithbiz', followersCount: 89000, engagement: 7.8, verified: true },
          { platform: 'youtube', handle: '@BusinessWithJordan', followersCount: 45000, engagement: 6.9 },
        ],
        categories: ['Business', 'Finance', 'Education'],
        portfolioHighlights: ['Forbes 30 Under 30', 'Business Podcast Host', 'Startup Accelerator Mentor'],
        avgDealValue: 5800,
        specialties: ['Business Strategy', 'Entrepreneurship', 'Leadership Training'],
      },
    },
    {
      _id: 'creator-015',
      name: 'Isabella Garcia',
      userName: '@plantmom_isa',
      avatarUrl: 'https://randomuser.me/api/portraits/women/15.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Plant Expert | Gardening Enthusiast | Sustainable Living Advocate',
      location: 'San Diego, CA',
      rating: 4.8,
      completedDeals: 27,
      responseTime: '3 hours',
      joinedDate: new Date('2022-04-18'),
      verified: true,
      creatorData: {
        totalFollowers: 178000,
        platforms: [
          { platform: 'instagram', handle: '@plantmom_isa', followersCount: 112000, engagement: 13.1, verified: true },
          { platform: 'youtube', handle: '@IsabellaGardens', followersCount: 66000, engagement: 8.3 },
        ],
        categories: ['Plants', 'Gardening', 'Sustainability'],
        portfolioHighlights: ['Botany Degree', 'Garden Center Partnership', 'Sustainable Living Expert'],
        avgDealValue: 2700,
        specialties: ['Plant Care', 'Garden Design', 'Sustainable Practices'],
      },
    },
    {
      _id: 'creator-016',
      name: 'Nathan Taylor',
      userName: '@coachnate',
      avatarUrl: 'https://randomuser.me/api/portraits/men/16.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Life Coach | Motivational Speaker | Personal Development Expert',
      location: 'Atlanta, GA',
      rating: 5.0,
      completedDeals: 42,
      responseTime: '45 minutes',
      joinedDate: new Date('2021-08-25'),
      verified: true,
      creatorData: {
        totalFollowers: 298000,
        platforms: [
          { platform: 'instagram', handle: '@coachnate', followersCount: 187000, engagement: 11.9, verified: true },
          { platform: 'linkedin', handle: '@nathantaylorcoach', followersCount: 111000, engagement: 8.2 },
        ],
        categories: ['Motivation', 'Education', 'Lifestyle'],
        portfolioHighlights: ['Best-Selling Author', 'Fortune 500 Speaker', 'Top Life Coach 2023'],
        avgDealValue: 4900,
        specialties: ['Personal Growth', 'Motivational Content', 'Career Development'],
      },
    },
    // INTERNATIONAL CREATORS - UK
    {
      _id: 'creator-017',
      name: 'Olivia Clarke',
      userName: '@livstyle_uk',
      avatarUrl: 'https://randomuser.me/api/portraits/women/17.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'British Fashion Blogger | Vintage Style Expert | London Street Fashion',
      location: 'London, UK',
      rating: 4.8,
      completedDeals: 25,
      responseTime: '2 hours',
      joinedDate: new Date('2022-09-12'),
      verified: true,
      creatorData: {
        totalFollowers: 87000,
        platforms: [
          { platform: 'instagram', handle: '@livstyle_uk', followersCount: 52000, engagement: 9.4, verified: true },
          { platform: 'pinterest', handle: '@oliviastyle', followersCount: 35000, engagement: 6.8 },
        ],
        categories: ['Fashion', 'Vintage', 'Lifestyle'],
        portfolioHighlights: ['British Vogue Feature', 'London Fashion Week', 'Vintage Style Award'],
        avgDealValue: 2100,
        specialties: ['Vintage Fashion', 'Street Style', 'British Fashion'],
        postingFrequency: 'Daily',
        country: 'UK',
        city: 'London',
        audienceGender: { male: 25, female: 75 },
        audienceAge: { min: 22, max: 35 },
        language: 'English',
        age: 26,
        audienceGroups: ['Millennials', 'Gen Z', 'Professionals'],
      },
    },
    {
      _id: 'creator-018',
      name: 'James Wilson',
      userName: '@jameseats_london',
      avatarUrl: 'https://randomuser.me/api/portraits/men/18.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'London Food Critic | British Cuisine Expert | Restaurant Reviewer',
      location: 'Manchester, UK',
      rating: 4.9,
      completedDeals: 31,
      responseTime: '1 hour',
      joinedDate: new Date('2021-06-18'),
      verified: true,
      creatorData: {
        totalFollowers: 156000,
        platforms: [
          { platform: 'youtube', handle: '@JamesEatsLondon', followersCount: 89000, engagement: 8.2, verified: true },
          { platform: 'instagram', handle: '@jameseats_london', followersCount: 67000, engagement: 10.1 },
        ],
        categories: ['Food', 'Travel', 'Culture'],
        portfolioHighlights: ['BBC Food Contributor', 'Michelin Restaurant Partner', 'UK Food Awards Judge'],
        avgDealValue: 3200,
        specialties: ['Restaurant Reviews', 'British Cuisine', 'Food Photography'],
        postingFrequency: 'Weekly',
        country: 'UK',
        city: 'Manchester',
        audienceGender: { male: 60, female: 40 },
        audienceAge: { min: 25, max: 45 },
        language: 'English',
        age: 32,
        audienceGroups: ['Millennials', 'Professionals'],
      },
    },
    // CANADA
    {
      _id: 'creator-019',
      name: 'Sarah Chen',
      userName: '@sarahfit_ca',
      avatarUrl: 'https://randomuser.me/api/portraits/women/19.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Canadian Fitness Coach | Winter Sports Enthusiast | Outdoor Adventure Guide',
      location: 'Toronto, Canada',
      rating: 4.7,
      completedDeals: 28,
      responseTime: '3 hours',
      joinedDate: new Date('2022-01-22'),
      verified: true,
      creatorData: {
        totalFollowers: 94000,
        platforms: [
          { platform: 'instagram', handle: '@sarahfit_ca', followersCount: 67000, engagement: 11.3, verified: true },
          { platform: 'tiktok', handle: '@sarahfitness', followersCount: 27000, engagement: 15.7 },
        ],
        categories: ['Fitness', 'Outdoor', 'Adventure'],
        portfolioHighlights: ['Canadian Fitness Awards', 'Winter Olympics Feature', 'Adventure Brand Partnerships'],
        avgDealValue: 2400,
        specialties: ['Winter Fitness', 'Outdoor Workouts', 'Adventure Gear'],
        postingFrequency: 'Daily',
        country: 'Canada',
        city: 'Toronto',
        audienceGender: { male: 45, female: 55 },
        audienceAge: { min: 20, max: 40 },
        language: 'English',
        age: 29,
        audienceGroups: ['Millennials', 'Gen Z'],
      },
    },
    {
      _id: 'creator-020',
      name: 'Lucas Dubois',
      userName: '@lucas_tech_montreal',
      avatarUrl: 'https://randomuser.me/api/portraits/men/20.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Canadian Tech Reviewer | AI Specialist | French-English Content Creator',
      location: 'Montreal, Canada',
      rating: 4.8,
      completedDeals: 22,
      responseTime: '4 hours',
      joinedDate: new Date('2022-07-08'),
      verified: true,
      creatorData: {
        totalFollowers: 78000,
        platforms: [
          { platform: 'youtube', handle: '@LucasTechMontreal', followersCount: 45000, engagement: 7.9, verified: true },
          { platform: 'linkedin', handle: '@lucasduboistech', followersCount: 33000, engagement: 5.2 },
        ],
        categories: ['Technology', 'AI', 'Education'],
        portfolioHighlights: ['McGill AI Research', 'Tech Conference Speaker', 'Bilingual Tech Content'],
        avgDealValue: 3600,
        specialties: ['AI Reviews', 'Tech Education', 'Bilingual Content'],
        postingFrequency: 'Bi-weekly',
        country: 'Canada',
        city: 'Montreal',
        audienceGender: { male: 70, female: 30 },
        audienceAge: { min: 22, max: 38 },
        language: 'French',
        age: 31,
        audienceGroups: ['Millennials', 'Professionals', 'Students'],
      },
    },
    // AUSTRALIA
    {
      _id: 'creator-021',
      name: 'Mia Thompson',
      userName: '@aussie_adventures',
      avatarUrl: 'https://randomuser.me/api/portraits/women/21.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Australian Travel Blogger | Wildlife Photographer | Outdoor Adventure Guide',
      location: 'Sydney, Australia',
      rating: 4.9,
      completedDeals: 35,
      responseTime: '2 hours',
      joinedDate: new Date('2021-11-15'),
      verified: true,
      creatorData: {
        totalFollowers: 203000,
        platforms: [
          { platform: 'instagram', handle: '@aussie_adventures', followersCount: 134000, engagement: 12.1, verified: true },
          { platform: 'youtube', handle: '@AussieAdventures', followersCount: 69000, engagement: 8.7 },
        ],
        categories: ['Travel', 'Wildlife', 'Adventure'],
        portfolioHighlights: ['Tourism Australia Partner', 'Wildlife Photography Awards', 'Great Barrier Reef Ambassador'],
        avgDealValue: 3800,
        specialties: ['Wildlife Photography', 'Adventure Travel', 'Australian Tourism'],
        postingFrequency: 'Weekly',
        country: 'Australia',
        city: 'Sydney',
        audienceGender: { male: 40, female: 60 },
        audienceAge: { min: 25, max: 50 },
        language: 'English',
        age: 28,
        audienceGroups: ['Millennials', 'Gen Z'],
      },
    },
    {
      _id: 'creator-022',
      name: 'Jack Murphy',
      userName: '@surflife_aus',
      avatarUrl: 'https://randomuser.me/api/portraits/men/22.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Professional Surfer | Australian Beach Culture | Surf Gear Reviewer',
      location: 'Gold Coast, Australia',
      rating: 4.6,
      completedDeals: 18,
      responseTime: '6 hours',
      joinedDate: new Date('2022-03-30'),
      verified: true,
      creatorData: {
        totalFollowers: 67000,
        platforms: [
          { platform: 'instagram', handle: '@surflife_aus', followersCount: 45000, engagement: 13.2, verified: true },
          { platform: 'tiktok', handle: '@jacksurfing', followersCount: 22000, engagement: 17.8 },
        ],
        categories: ['Sports', 'Lifestyle', 'Adventure'],
        portfolioHighlights: ['World Surf League', 'Surfboard Brand Ambassador', 'Australian Surf Champion'],
        avgDealValue: 2800,
        specialties: ['Surf Gear', 'Beach Lifestyle', 'Water Sports'],
        postingFrequency: 'Daily',
        country: 'Australia',
        city: 'Gold Coast',
        audienceGender: { male: 65, female: 35 },
        audienceAge: { min: 18, max: 35 },
        language: 'English',
        age: 25,
        audienceGroups: ['Gen Z', 'Millennials'],
      },
    },
    // GERMANY
    {
      _id: 'creator-023',
      name: 'Anna Mueller',
      userName: '@anna_eco_berlin',
      avatarUrl: 'https://randomuser.me/api/portraits/women/23.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'German Sustainability Expert | Eco-Fashion Advocate | Zero Waste Lifestyle',
      location: 'Berlin, Germany',
      rating: 4.9,
      completedDeals: 33,
      responseTime: '2 hours',
      joinedDate: new Date('2021-08-14'),
      verified: true,
      creatorData: {
        totalFollowers: 128000,
        platforms: [
          { platform: 'instagram', handle: '@anna_eco_berlin', followersCount: 89000, engagement: 14.5, verified: true },
          { platform: 'youtube', handle: '@AnnaEcoLife', followersCount: 39000, engagement: 9.1 },
        ],
        categories: ['Sustainability', 'Fashion', 'Lifestyle'],
        portfolioHighlights: ['EU Environmental Award', 'Sustainable Fashion Week', 'Green Living Expert'],
        avgDealValue: 3100,
        specialties: ['Sustainable Fashion', 'Zero Waste', 'Eco-Friendly Products'],
        postingFrequency: 'Weekly',
        country: 'Germany',
        city: 'Berlin',
        audienceGender: { male: 20, female: 80 },
        audienceAge: { min: 24, max: 45 },
        language: 'German',
        age: 30,
        audienceGroups: ['Millennials', 'Professionals'],
      },
    },
    {
      _id: 'creator-024',
      name: 'Stefan Weber',
      userName: '@gaming_stefan_de',
      avatarUrl: 'https://randomuser.me/api/portraits/men/24.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'German Gaming Expert | Esports Commentator | Game Development Insights',
      location: 'Munich, Germany',
      rating: 4.7,
      completedDeals: 26,
      responseTime: '3 hours',
      joinedDate: new Date('2022-02-11'),
      verified: true,
      creatorData: {
        totalFollowers: 145000,
        platforms: [
          { platform: 'twitch', handle: '@gaming_stefan', followersCount: 89000, engagement: 16.3, verified: true },
          { platform: 'youtube', handle: '@StefanGamingDE', followersCount: 56000, engagement: 10.2 },
        ],
        categories: ['Gaming', 'Esports', 'Technology'],
        portfolioHighlights: ['Gamescom Speaker', 'ESL Tournament Host', 'Gaming Hardware Partner'],
        avgDealValue: 4200,
        specialties: ['Game Reviews', 'Live Streaming', 'Gaming Hardware'],
        postingFrequency: 'Daily',
        country: 'Germany',
        city: 'Munich',
        audienceGender: { male: 75, female: 25 },
        audienceAge: { min: 16, max: 30 },
        language: 'German',
        age: 27,
        audienceGroups: ['Gen Z', 'Students'],
      },
    },
    // FRANCE
    {
      _id: 'creator-025',
      name: 'Camille Dubois',
      userName: '@camille_paris_style',
      avatarUrl: 'https://randomuser.me/api/portraits/women/25.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Parisian Fashion Influencer | Luxury Style Expert | French Elegance',
      location: 'Paris, France',
      rating: 5.0,
      completedDeals: 41,
      responseTime: '1 hour',
      joinedDate: new Date('2021-05-20'),
      verified: true,
      creatorData: {
        totalFollowers: 234000,
        platforms: [
          { platform: 'instagram', handle: '@camille_paris_style', followersCount: 167000, engagement: 11.8, verified: true },
          { platform: 'pinterest', handle: '@camillestyle', followersCount: 67000, engagement: 7.4 },
        ],
        categories: ['Fashion', 'Luxury', 'Lifestyle'],
        portfolioHighlights: ['Paris Fashion Week', 'Chanel Partnership', 'French Elle Feature'],
        avgDealValue: 5200,
        specialties: ['Luxury Fashion', 'Parisian Style', 'Fashion Photography'],
        postingFrequency: 'Daily',
        country: 'France',
        city: 'Paris',
        audienceGender: { male: 15, female: 85 },
        audienceAge: { min: 25, max: 50 },
        language: 'French',
        age: 29,
        audienceGroups: ['Millennials', 'Professionals'],
      },
    },
    {
      _id: 'creator-026',
      name: 'Pierre Martin',
      userName: '@chef_pierre_lyon',
      avatarUrl: 'https://randomuser.me/api/portraits/men/26.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'French Chef | Culinary Arts Expert | Traditional French Cuisine',
      location: 'Lyon, France',
      rating: 4.8,
      completedDeals: 29,
      responseTime: '4 hours',
      joinedDate: new Date('2021-09-05'),
      verified: true,
      creatorData: {
        totalFollowers: 112000,
        platforms: [
          { platform: 'instagram', handle: '@chef_pierre_lyon', followersCount: 78000, engagement: 12.6, verified: true },
          { platform: 'youtube', handle: '@ChefPierreLyon', followersCount: 34000, engagement: 8.9 },
        ],
        categories: ['Food', 'Cooking', 'Culture'],
        portfolioHighlights: ['Michelin Star Restaurant', 'French Culinary Institute', 'Le Cordon Bleu Graduate'],
        avgDealValue: 3700,
        specialties: ['French Cuisine', 'Cooking Techniques', 'Wine Pairing'],
        postingFrequency: 'Bi-weekly',
        country: 'France',
        city: 'Lyon',
        audienceGender: { male: 55, female: 45 },
        audienceAge: { min: 28, max: 55 },
        language: 'French',
        age: 35,
        audienceGroups: ['Millennials', 'Professionals'],
      },
    },
    // BRAZIL
    {
      _id: 'creator-027',
      name: 'Isabella Santos',
      userName: '@bella_fitness_br',
      avatarUrl: 'https://randomuser.me/api/portraits/women/27.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Brazilian Fitness Model | Beach Workouts | Wellness Coach',
      location: 'Rio de Janeiro, Brazil',
      rating: 4.9,
      completedDeals: 37,
      responseTime: '2 hours',
      joinedDate: new Date('2021-12-18'),
      verified: true,
      creatorData: {
        totalFollowers: 189000,
        platforms: [
          { platform: 'instagram', handle: '@bella_fitness_br', followersCount: 134000, engagement: 15.2, verified: true },
          { platform: 'tiktok', handle: '@bellafitness', followersCount: 55000, engagement: 18.7 },
        ],
        categories: ['Fitness', 'Beach', 'Wellness'],
        portfolioHighlights: ['Brazilian Fitness Awards', 'Rio Beach Ambassador', 'Wellness Brand Partner'],
        avgDealValue: 2900,
        specialties: ['Beach Workouts', 'Brazilian Fitness', 'Wellness Coaching'],
        postingFrequency: 'Daily',
        country: 'Brazil',
        city: 'Rio de Janeiro',
        audienceGender: { male: 30, female: 70 },
        audienceAge: { min: 18, max: 35 },
        language: 'Portuguese',
        age: 26,
        audienceGroups: ['Gen Z', 'Millennials'],
      },
    },
    {
      _id: 'creator-028',
      name: 'Carlos Silva',
      userName: '@carlos_music_sp',
      avatarUrl: 'https://randomuser.me/api/portraits/men/28.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Brazilian Music Producer | Samba & Electronic Fusion | Music Education',
      location: 'São Paulo, Brazil',
      rating: 4.7,
      completedDeals: 23,
      responseTime: '5 hours',
      joinedDate: new Date('2022-04-07'),
      verified: true,
      creatorData: {
        totalFollowers: 98000,
        platforms: [
          { platform: 'youtube', handle: '@CarlosMusicSP', followersCount: 67000, engagement: 11.4, verified: true },
          { platform: 'instagram', handle: '@carlos_music_sp', followersCount: 31000, engagement: 13.8 },
        ],
        categories: ['Music', 'Education', 'Culture'],
        portfolioHighlights: ['Brazilian Music Awards', 'Samba School Partnership', 'Music Production Courses'],
        avgDealValue: 3400,
        specialties: ['Music Production', 'Brazilian Music', 'Audio Engineering'],
        postingFrequency: 'Weekly',
        country: 'Brazil',
        city: 'São Paulo',
        audienceGender: { male: 60, female: 40 },
        audienceAge: { min: 20, max: 40 },
        language: 'Portuguese',
        age: 31,
        audienceGroups: ['Millennials', 'Gen Z', 'Students'],
      },
    },
    // JAPAN
    {
      _id: 'creator-029',
      name: 'Yuki Tanaka',
      userName: '@yuki_kawaii_tokyo',
      avatarUrl: 'https://randomuser.me/api/portraits/women/29.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Japanese Kawaii Culture Expert | Anime & Manga Reviewer | Tokyo Street Fashion',
      location: 'Tokyo, Japan',
      rating: 4.8,
      completedDeals: 31,
      responseTime: '3 hours',
      joinedDate: new Date('2021-10-25'),
      verified: true,
      creatorData: {
        totalFollowers: 167000,
        platforms: [
          { platform: 'instagram', handle: '@yuki_kawaii_tokyo', followersCount: 98000, engagement: 16.9, verified: true },
          { platform: 'tiktok', handle: '@yukikawaii', followersCount: 69000, engagement: 19.3 },
        ],
        categories: ['Fashion', 'Anime', 'Culture'],
        portfolioHighlights: ['Tokyo Fashion Week', 'Anime Expo Speaker', 'Kawaii Culture Ambassador'],
        avgDealValue: 3800,
        specialties: ['Kawaii Fashion', 'Anime Reviews', 'Japanese Culture'],
        postingFrequency: 'Daily',
        country: 'Japan',
        city: 'Tokyo',
        audienceGender: { male: 25, female: 75 },
        audienceAge: { min: 16, max: 28 },
        language: 'Japanese',
        age: 24,
        audienceGroups: ['Gen Z', 'Students'],
      },
    },
    {
      _id: 'creator-030',
      name: 'Hiroshi Yamamoto',
      userName: '@hiroshi_tech_osaka',
      avatarUrl: 'https://randomuser.me/api/portraits/men/30.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Japanese Tech Innovation Expert | Robotics Enthusiast | Future Technology',
      location: 'Osaka, Japan',
      rating: 4.9,
      completedDeals: 28,
      responseTime: '2 hours',
      joinedDate: new Date('2022-01-14'),
      verified: true,
      creatorData: {
        totalFollowers: 134000,
        platforms: [
          { platform: 'youtube', handle: '@HiroshiTechOsaka', followersCount: 89000, engagement: 9.7, verified: true },
          { platform: 'linkedin', handle: '@hiroshiyamamoto', followersCount: 45000, engagement: 6.8 },
        ],
        categories: ['Technology', 'Robotics', 'Innovation'],
        portfolioHighlights: ['Sony Tech Partner', 'Robotics Conference Speaker', 'Japanese Innovation Award'],
        avgDealValue: 4600,
        specialties: ['Robotics', 'Tech Innovation', 'Japanese Technology'],
        postingFrequency: 'Bi-weekly',
        country: 'Japan',
        city: 'Osaka',
        audienceGender: { male: 70, female: 30 },
        audienceAge: { min: 25, max: 45 },
        language: 'Japanese',
        age: 33,
        audienceGroups: ['Millennials', 'Professionals'],
      },
    },
    // INDIA
    {
      _id: 'creator-031',
      name: 'Priya Sharma',
      userName: '@priya_bollywood_dance',
      avatarUrl: 'https://randomuser.me/api/portraits/women/31.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Bollywood Dance Choreographer | Indian Classical Dance | Dance Education',
      location: 'Mumbai, India',
      rating: 4.9,
      completedDeals: 42,
      responseTime: '2 hours',
      joinedDate: new Date('2021-07-22'),
      verified: true,
      creatorData: {
        totalFollowers: 201000,
        platforms: [
          { platform: 'instagram', handle: '@priya_bollywood_dance', followersCount: 145000, engagement: 17.2, verified: true },
          { platform: 'youtube', handle: '@PriyaDanceStudio', followersCount: 56000, engagement: 12.1 },
        ],
        categories: ['Dance', 'Culture', 'Education'],
        portfolioHighlights: ['Bollywood Film Choreographer', 'Indian Dance Academy', 'Cultural Ambassador'],
        avgDealValue: 2600,
        specialties: ['Bollywood Dance', 'Classical Indian Dance', 'Dance Education'],
        postingFrequency: 'Daily',
        country: 'India',
        city: 'Mumbai',
        audienceGender: { male: 35, female: 65 },
        audienceAge: { min: 18, max: 35 },
        language: 'English',
        age: 27,
        audienceGroups: ['Gen Z', 'Millennials', 'Students'],
      },
    },
    {
      _id: 'creator-032',
      name: 'Arjun Patel',
      userName: '@arjun_startup_bangalore',
      avatarUrl: 'https://randomuser.me/api/portraits/men/32.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Indian Tech Entrepreneur | Startup Advisor | Business Innovation Expert',
      location: 'Bangalore, India',
      rating: 4.8,
      completedDeals: 24,
      responseTime: '4 hours',
      joinedDate: new Date('2022-03-16'),
      verified: true,
      creatorData: {
        totalFollowers: 87000,
        platforms: [
          { platform: 'linkedin', handle: '@arjunpatelstartup', followersCount: 56000, engagement: 8.4, verified: true },
          { platform: 'youtube', handle: '@ArjunStartupTalks', followersCount: 31000, engagement: 7.1 },
        ],
        categories: ['Business', 'Technology', 'Education'],
        portfolioHighlights: ['Y Combinator Mentor', 'Indian Startup Awards', 'Tech Conference Speaker'],
        avgDealValue: 4100,
        specialties: ['Startup Strategy', 'Tech Innovation', 'Business Development'],
        postingFrequency: 'Weekly',
        country: 'India',
        city: 'Bangalore',
        audienceGender: { male: 65, female: 35 },
        audienceAge: { min: 22, max: 40 },
        language: 'English',
        age: 30,
        audienceGroups: ['Millennials', 'Professionals', 'Students'],
      },
    },
    // MEXICO
    {
      _id: 'creator-033',
      name: 'Maria Gonzalez',
      userName: '@maria_cocina_mx',
      avatarUrl: 'https://randomuser.me/api/portraits/women/33.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Mexican Cuisine Expert | Traditional Recipes | Cooking Education',
      location: 'Mexico City, Mexico',
      rating: 4.9,
      completedDeals: 38,
      responseTime: '2 hours',
      joinedDate: new Date('2021-11-08'),
      verified: true,
      creatorData: {
        totalFollowers: 156000,
        platforms: [
          { platform: 'instagram', handle: '@maria_cocina_mx', followersCount: 112000, engagement: 14.8, verified: true },
          { platform: 'youtube', handle: '@MariaCocinaTradicional', followersCount: 44000, engagement: 10.3 },
        ],
        categories: ['Food', 'Culture', 'Education'],
        portfolioHighlights: ['Mexican Culinary Institute', 'Traditional Recipe Book', 'Cultural Food Ambassador'],
        avgDealValue: 2800,
        specialties: ['Mexican Cuisine', 'Traditional Recipes', 'Cooking Education'],
        postingFrequency: 'Weekly',
        country: 'Mexico',
        city: 'Mexico City',
        audienceGender: { male: 25, female: 75 },
        audienceAge: { min: 25, max: 50 },
        language: 'Spanish',
        age: 32,
        audienceGroups: ['Millennials', 'Parents', 'Professionals'],
      },
    },
    {
      _id: 'creator-034',
      name: 'Diego Rivera',
      userName: '@diego_arte_guadalajara',
      avatarUrl: 'https://randomuser.me/api/portraits/men/34.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Mexican Artist | Street Art Expert | Art Education | Cultural Heritage',
      location: 'Guadalajara, Mexico',
      rating: 4.7,
      completedDeals: 19,
      responseTime: '5 hours',
      joinedDate: new Date('2022-06-12'),
      verified: true,
      creatorData: {
        totalFollowers: 73000,
        platforms: [
          { platform: 'instagram', handle: '@diego_arte_guadalajara', followersCount: 52000, engagement: 15.6, verified: true },
          { platform: 'tiktok', handle: '@diegoarte', followersCount: 21000, engagement: 17.9 },
        ],
        categories: ['Art', 'Culture', 'Education'],
        portfolioHighlights: ['Mexican Art Gallery', 'Street Art Festival', 'Cultural Heritage Project'],
        avgDealValue: 2200,
        specialties: ['Street Art', 'Mexican Culture', 'Art Education'],
        postingFrequency: 'Bi-weekly',
        country: 'Mexico',
        city: 'Guadalajara',
        audienceGender: { male: 45, female: 55 },
        audienceAge: { min: 20, max: 40 },
        language: 'Spanish',
        age: 28,
        audienceGroups: ['Millennials', 'Gen Z', 'Students'],
      },
    },
    // NANO INFLUENCERS (1K-10K)
    {
      _id: 'creator-035',
      name: 'Lily Wang',
      userName: '@lily_minimalist_sf',
      avatarUrl: 'https://randomuser.me/api/portraits/women/35.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Minimalist Lifestyle | Sustainable Living | Small Space Design',
      location: 'San Francisco, CA',
      rating: 4.6,
      completedDeals: 12,
      responseTime: '1 hour',
      joinedDate: new Date('2023-01-20'),
      verified: false,
      creatorData: {
        totalFollowers: 8400,
        platforms: [
          { platform: 'instagram', handle: '@lily_minimalist_sf', followersCount: 5200, engagement: 18.3 },
          { platform: 'pinterest', handle: '@lilyminimalist', followersCount: 3200, engagement: 12.7 },
        ],
        categories: ['Lifestyle', 'Minimalism', 'Design'],
        portfolioHighlights: ['Minimalist Living Blog', 'Small Space Expert', 'Sustainable Brand Partner'],
        avgDealValue: 450,
        specialties: ['Minimalist Design', 'Small Space Solutions', 'Sustainable Products'],
        postingFrequency: 'Daily',
        country: 'USA',
        city: 'San Francisco',
        audienceGender: { male: 20, female: 80 },
        audienceAge: { min: 25, max: 40 },
        language: 'English',
        age: 26,
        audienceGroups: ['Millennials', 'Professionals'],
      },
    },
    {
      _id: 'creator-036',
      name: 'Tom Baker',
      userName: '@tom_local_foodie',
      avatarUrl: 'https://randomuser.me/api/portraits/men/36.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Local Food Explorer | Hidden Gems | Community Restaurant Reviews',
      location: 'Portland, OR',
      rating: 4.8,
      completedDeals: 15,
      responseTime: '2 hours',
      joinedDate: new Date('2022-11-30'),
      verified: false,
      creatorData: {
        totalFollowers: 6700,
        platforms: [
          { platform: 'instagram', handle: '@tom_local_foodie', followersCount: 4100, engagement: 22.1 },
          { platform: 'tiktok', handle: '@tomfoodie', followersCount: 2600, engagement: 24.8 },
        ],
        categories: ['Food', 'Local', 'Reviews'],
        portfolioHighlights: ['Portland Food Guide', 'Local Restaurant Partner', 'Community Food Awards'],
        avgDealValue: 380,
        specialties: ['Local Restaurants', 'Food Photography', 'Community Reviews'],
        postingFrequency: 'Daily',
        country: 'USA',
        city: 'Portland',
        audienceGender: { male: 50, female: 50 },
        audienceAge: { min: 22, max: 45 },
        language: 'English',
        age: 29,
        audienceGroups: ['Millennials', 'Gen Z'],
      },
    },
    // MEGA INFLUENCERS (1M+)
    {
      _id: 'creator-037',
      name: 'Alexandra Stone',
      userName: '@alexandra_global_fashion',
      avatarUrl: 'https://randomuser.me/api/portraits/women/37.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Global Fashion Icon | International Style Expert | Luxury Brand Ambassador',
      location: 'New York, NY',
      rating: 5.0,
      completedDeals: 67,
      responseTime: '30 minutes',
      joinedDate: new Date('2020-03-15'),
      verified: true,
      creatorData: {
        totalFollowers: 2340000,
        platforms: [
          { platform: 'instagram', handle: '@alexandra_global_fashion', followersCount: 1890000, engagement: 6.8, verified: true },
          { platform: 'tiktok', handle: '@alexandrastyle', followersCount: 450000, engagement: 9.2 },
        ],
        categories: ['Fashion', 'Luxury', 'Travel'],
        portfolioHighlights: ['Vogue Cover Model', 'Paris Fashion Week Ambassador', 'Global Brand Partnerships'],
        avgDealValue: 25000,
        specialties: ['High Fashion', 'Luxury Brands', 'International Fashion'],
        postingFrequency: 'Daily',
        country: 'USA',
        city: 'New York',
        audienceGender: { male: 10, female: 90 },
        audienceAge: { min: 18, max: 45 },
        language: 'English',
        age: 28,
        audienceGroups: ['Gen Z', 'Millennials', 'Professionals'],
      },
    },
    {
      _id: 'creator-038',
      name: 'Ryan Mitchell',
      userName: '@ryan_global_gaming',
      avatarUrl: 'https://randomuser.me/api/portraits/men/38.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Global Gaming Superstar | Esports Champion | Gaming Content Creator',
      location: 'Los Angeles, CA',
      rating: 4.9,
      completedDeals: 54,
      responseTime: '1 hour',
      joinedDate: new Date('2019-08-22'),
      verified: true,
      creatorData: {
        totalFollowers: 3120000,
        platforms: [
          { platform: 'twitch', handle: '@ryangaming', followersCount: 1890000, engagement: 12.4, verified: true },
          { platform: 'youtube', handle: '@RyanGlobalGaming', followersCount: 1230000, engagement: 8.7, verified: true },
        ],
        categories: ['Gaming', 'Esports', 'Entertainment'],
        portfolioHighlights: ['World Gaming Champion', 'Major Esports Partner', 'Gaming Industry Award'],
        avgDealValue: 35000,
        specialties: ['Live Gaming', 'Esports Tournaments', 'Gaming Hardware'],
        postingFrequency: 'Daily',
        country: 'USA',
        city: 'Los Angeles',
        audienceGender: { male: 78, female: 22 },
        audienceAge: { min: 13, max: 30 },
        language: 'English',
        age: 24,
        audienceGroups: ['Gen Z', 'Students'],
      },
    },
    // ADDITIONAL PLATFORM DIVERSITY
    {
      _id: 'creator-039',
      name: 'Rebecca Foster',
      userName: '@rebecca_professional_network',
      avatarUrl: 'https://randomuser.me/api/portraits/women/39.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Corporate Leadership Expert | Professional Development | Career Coach',
      location: 'Chicago, IL',
      rating: 4.9,
      completedDeals: 32,
      responseTime: '2 hours',
      joinedDate: new Date('2021-04-18'),
      verified: true,
      creatorData: {
        totalFollowers: 145000,
        platforms: [
          { platform: 'linkedin', handle: '@rebeccafostercareers', followersCount: 98000, engagement: 9.1, verified: true },
          { platform: 'facebook', handle: '@rebeccacareercoach', followersCount: 47000, engagement: 5.3 },
        ],
        categories: ['Business', 'Career', 'Education'],
        portfolioHighlights: ['Fortune 500 Consultant', 'Leadership Development Expert', 'Corporate Training'],
        avgDealValue: 5800,
        specialties: ['Leadership Development', 'Career Coaching', 'Professional Skills'],
        postingFrequency: 'Weekly',
        country: 'USA',
        city: 'Chicago',
        audienceGender: { male: 45, female: 55 },
        audienceAge: { min: 25, max: 50 },
        language: 'English',
        age: 34,
        audienceGroups: ['Millennials', 'Professionals'],
      },
    },
    {
      _id: 'creator-040',
      name: 'Kevin Zhang',
      userName: '@kevin_snapchat_creator',
      avatarUrl: 'https://randomuser.me/api/portraits/men/40.jpg',
      isActive: true,
      userType: 'Creator',
      bio: 'Gen Z Content Creator | Snapchat Expert | Short-Form Video Specialist',
      location: 'Miami, FL',
      rating: 4.6,
      completedDeals: 28,
      responseTime: '1 hour',
      joinedDate: new Date('2022-08-05'),
      verified: true,
      creatorData: {
        totalFollowers: 234000,
        platforms: [
          { platform: 'snapchat', handle: '@kevinzsnaps', followersCount: 156000, engagement: 14.7 },
          { platform: 'tiktok', handle: '@kevinzhang', followersCount: 78000, engagement: 16.2 },
        ],
        categories: ['Entertainment', 'Lifestyle', 'Comedy'],
        portfolioHighlights: ['Snapchat Featured Creator', 'Gen Z Marketing Expert', 'Viral Content Creator'],
        avgDealValue: 3200,
        specialties: ['Short-Form Content', 'Gen Z Marketing', 'Social Media Trends'],
        postingFrequency: 'Daily',
        country: 'USA',
        city: 'Miami',
        audienceGender: { male: 48, female: 52 },
        audienceAge: { min: 16, max: 25 },
        language: 'English',
        age: 21,
        audienceGroups: ['Gen Z', 'Students'],
      },
    },
  ],

  // Analytics Data
  analytics: {
    overview: {
      totalRevenue: 485600,
      monthlyGrowth: 23.5,
      activeUsers: 3420,
      completedDeals: 892,
    },
    recentActivity: [
      { type: 'deal_completed', amount: 3500, time: '2 hours ago', creator: 'Emma Thompson' },
      { type: 'payment_sent', amount: 2800, time: '5 hours ago', creator: 'Marcus Johnson' },
      { type: 'offer_accepted', amount: 4200, time: '1 day ago', creator: 'Sofia Rodriguez' },
      { type: 'milestone_completed', amount: 1500, time: '2 days ago', creator: 'Alex Chen' },
    ],
    performanceMetrics: {
      avgDealCompletion: 8.5, // days
      creatorSatisfaction: 4.8,
      brandRetention: 92,
      platformGrowth: 156, // percentage YoY
    },
  },

  // Demo Notifications
  notifications: [
    {
      id: 'notif-001',
      type: 'application',
      message: 'Emma Thompson applied to your Summer Collection offer',
      time: '2 minutes ago',
      unread: true,
    },
    {
      id: 'notif-002',
      type: 'milestone',
      message: 'Marcus Johnson completed the product review',
      time: '1 hour ago',
      unread: true,
    },
    {
      id: 'notif-003',
      type: 'payment',
      message: 'Payment of $3,500 processed successfully',
      time: '3 hours ago',
      unread: false,
    },
  ],

  // Success Messages
  successMessages: {
    offerCreated: 'Offer published! 23 creators viewing now',
    applicationAccepted: 'Great choice! Emma Thompson is perfect for this campaign',
    paymentProcessed: 'Payment successful! Campaign is now live',
    dealCompleted: 'Congratulations! Another successful collaboration',
  },
};